dist: bionic
sudo: required
language: python
python:
- '3.6'
- '3.7'
- '3.8'
env:
  matrix:
  - DJANGO_VERSION=2.2.*
  - DJANGO_VERSION=3.0.*
  - DJANGO_VERSION=dev
services:
- postgresql
addons:
  postgresql: '10'
stages:
- lint
- test
- deploy
install:
- pip install -e .[dev]
- pip install coverage codecov
- if [[ $DJANGO_VERSION == dev ]]; then pip install -e git+https://github.com/django/django@master#egg=django;
  else pip install Django==$DJANGO_VERSION -U; fi
before_script:
- psql -c "CREATE USER travis_ci_test WITH ENCRYPTED PASSWORD 'travis_ci_test';" -U
  postgres
- psql -c "ALTER USER travis_ci_test WITH SUPERUSER;" -U postgres
- psql -c 'CREATE DATABASE travis_ci_test WITH OWNER travis_ci_test;' -U postgres
after_failure:
- pip freeze
script:
- coverage run ./manage.py test
- codecov
jobs:
  allow_failures:
  - env: DJANGO_VERSION=dev
  include:
  - stage: lint
    install:
    - pip install flake8
    before_script: skip
    script:
    - flake8 datastore
  - stage: deploy
    install: skip
    before_script: skip
    script: skip
    deploy:
      stage: deploy
      provider: pypi
      user: __token__
      password:
        secure: JA4qz55euQV03Ra01XxVQ4LKOv+1cKwF9reIS7x50J7bI1huypaUafVRy9m1vupF7GfilYyd/PaMbvuOc2Igg93ugIgkdowZVW4N+ehbH1ZDQ21MvpvhS5QAfbn3HgF9N97dSOpKObSgpg7tl4nIeUEnd97JECfexzj0hhZOBESLTSQ/gJrd7s886NJVY2GMu+2f+7mcFNteq/Ev3x0nORk7niUWPenl2oam1gGUjRI3wVsrHzU7/8Dv2SgaW0IfwmCHNpV2sTEBGiMXOMg/hpMs2XcYymmUEpY0/EubSJMpTEUlhypKpwuwF4FUl1mQ+L/t/lQ+Z8wN0FZ0LTT09xehpyASH8AIGjiD48DJu/aN668SOL/YZ5WpuwEh17/MsXcT5dHbhYuZLA4yYrGx/l9RUpQVYOL56L7Ho986QzU5b1CHHu2rxQGrK1+zEE1othtxQtr0BDr/iKvG9M1Fysb7MbFBNYtpJqQIuE4SMUB8Udky4Pa0MHUFBDFKBXpq5yBOcOpl9dysU/8X6SHDjC2egdLSgulIbRVcyACoPDvV7Fpy896/gM3liO6EgDRlT8yN96OSP9zs0zgpYJ12B+xhHaNKY0drtM7k48zSNAKLPBAQyBvZYLZABbdKTto6hQ2PVQ2Hax0RojHtSrI6Ts6m8nG9dbTagXpMoiQQGAs=
      on:
        tags: true
