# Generated by Django 2.0.13 on 2019-07-15 12:10

from django.db import migrations
try:
    from django.db.models import JSONField
except ImportError:  # TODO Remove when dropping Django releases < 3.1
    from django.contrib.postgres.fields.jsonb import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0003_auto_20181120_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='relateddocument',
            name='properties',
            field=JSONField(default=dict),
        ),
    ]
